In [3]:
import pandas 
import numpy
df = pandas.read_csv('NFLdataset1.csv')

In [4]:
import pandas as pd
import numpy as np

In [5]:
df.head()

,Unnamed: 0,date,away,home,first_downs_away,first_downs_home,third_downs_away,third_downs_home,fourth_downs_away,fourth_downs_home,...,Home_attempts,away_attempts_completed,away_attempts,YPPA_away,YPPA_home,Average_Yards_Per_Rush_Attempt_Home,Average_Yards_Per_Rush_Attempt_Away,Pts_Per_Drive_home,Pts_Per_Drive_away,Home_Result
0,0,2002-09-05,49ers,Giants,13,21,4-12,9-16,0-0,0-1,...,45,16,26,6.4,7.1,2.0,4.5,0.87,1.23,Loss
1,1,2002-09-08,Jets,Bills,18,26,2-8,7-17,0-0,2-2,...,39,24,30,6.4,6.2,4.4,5.2,1.72,2.18,Loss
2,2,2002-09-08,Vikings,Bears,19,20,5-13,7-13,0-0,0-0,...,33,16,28,8.1,8.7,3.1,4.2,1.59,1.35,Win
3,3,2002-09-08,Chargers,Bengals,27,13,6-10,4-11,0-0,0-0,...,31,15,19,8.4,5.4,2.8,5.4,0.40,3.09,Loss
4,4,2002-09-08,Chiefs,Browns,24,24,5-11,4-11,0-0,0-0,...,40,20,29,9.5,8.8,3.0,6.5,2.29,2.00,Loss

In [6]:
df['date'] = pd.to_datetime(df['date'])

In [7]:
print(df.head(5))

   Unnamed: 0       date      away     home  first_downs_away  \
0           0 2002-09-05     49ers   Giants                13
1           1 2002-09-08      Jets    Bills                18
2           2 2002-09-08   Vikings    Bears                19
3           3 2002-09-08  Chargers  Bengals                27
4           4 2002-09-08    Chiefs   Browns                24

   first_downs_home third_downs_away third_downs_home fourth_downs_away  \
0                21             4-12             9-16               0-0
1                26              2-8             7-17               0-0
2                20             5-13             7-13               0-0
3                13             6-10             4-11               0-0
4                24             5-11             4-11               0-0

  fourth_downs_home  ...  Home_attempts  away_attempts_completed  \
0               0-1  ...             45                       16
1               2-2  ...             39                       24
2               0-0  ...             33                       16
3               0-0  ...             31                       15
4               0-0  ...             40                       20

   away_attempts  YPPA_away  YPPA_home  Average_Yards_Per_Rush_Attempt_Home  \
0             26        6.4        7.1                                  2.0
1             30        6.4        6.2                                  4.4
2             28        8.1        8.7                                  3.1
3             19        8.4        5.4                                  2.8
4             29        9.5        8.8                                  3.0

  Average_Yards_Per_Rush_Attempt_Away Pts_Per_Drive_home Pts_Per_Drive_away  \
0                                 4.5               0.87               1.23
1                                 5.2               1.72               2.18
2                                 4.2               1.59               1.35
3                                 5.4               0.40               3.09
4                                 6.5               2.29               2.00

  Home_Result
0        Loss
1        Loss
2         Win
3        Loss
4        Loss

[5 rows x 51 columns]

In [8]:
df.set_index(['season', 'team_name', 'game_id'], inplace=True)
df.sort_index(inplace=True)

KeyError: "None of ['season', 'team_name', 'game_id'] are in the columns"

In [9]:
import datetime

In [18]:
df.dtypes

Unnamed: 0                                      int64
date                                   datetime64[ns]
away                                           object
home                                           object
first_downs_away                                int64
first_downs_home                                int64
third_downs_away                               object
third_downs_home                               object
fourth_downs_away                              object
fourth_downs_home                              object
passing_yards_away                              int64
passing_yards_home                              int64
rushing_yards_away                              int64
rushing_yards_home                              int64
total_yards_away                                int64
total_yards_home                                int64
comp_att_away                                  object
comp_att_home                                  object
sacks_away                                     object
sacks_home                                     object
rushing_attempts_away                           int64
rushing_attempts_home                           int64
fumbles_away                                    int64
fumbles_home                                    int64
int_away                                        int64
int_home                                        int64
turnovers_away                                  int64
turnovers_home                                  int64
penalties_away                                 object
penalties_home                                 object
redzone_away                                   object
redzone_home                                   object
drives_away                                     int64
drives_home                                     int64
def_st_td_away                                  int64
def_st_td_home                                  int64
possession_away                                object
possession_home                                object
score_away                                      int64
score_home                                      int64
Home_attempts_completed                         int64
Home_attempts                                   int64
away_attempts_completed                         int64
away_attempts                                   int64
YPPA_away                                     float64
YPPA_home                                     float64
Average_Yards_Per_Rush_Attempt_Home           float64
Average_Yards_Per_Rush_Attempt_Away           float64
Pts_Per_Drive_home                            float64
Pts_Per_Drive_away                            float64
Home_Result                                    object
dtype: object

In [20]:
df.date.dt.week

0       36
1       36
2       36
3       36
4       36
        ..
4623    41
4624    41
4625    41
4626    41
4627    42
Name: date, Length: 4628, dtype: int64

In [21]:
df.head()

,Unnamed: 0,date,away,home,first_downs_away,first_downs_home,third_downs_away,third_downs_home,fourth_downs_away,fourth_downs_home,...,Home_attempts,away_attempts_completed,away_attempts,YPPA_away,YPPA_home,Average_Yards_Per_Rush_Attempt_Home,Average_Yards_Per_Rush_Attempt_Away,Pts_Per_Drive_home,Pts_Per_Drive_away,Home_Result
0,0,2002-09-05,49ers,Giants,13,21,4-12,9-16,0-0,0-1,...,45,16,26,6.4,7.1,2.0,4.5,0.87,1.23,Loss
1,1,2002-09-08,Jets,Bills,18,26,2-8,7-17,0-0,2-2,...,39,24,30,6.4,6.2,4.4,5.2,1.72,2.18,Loss
2,2,2002-09-08,Vikings,Bears,19,20,5-13,7-13,0-0,0-0,...,33,16,28,8.1,8.7,3.1,4.2,1.59,1.35,Win
3,3,2002-09-08,Chargers,Bengals,27,13,6-10,4-11,0-0,0-0,...,31,15,19,8.4,5.4,2.8,5.4,0.40,3.09,Loss
4,4,2002-09-08,Chiefs,Browns,24,24,5-11,4-11,0-0,0-0,...,40,20,29,9.5,8.8,3.0,6.5,2.29,2.00,Loss

In [22]:
df.columns()

TypeError: 'Index' object is not callable

In [25]:
list(df.columns)

['Unnamed: 0',
 'date',
 'away',
 'home',
 'first_downs_away',
 'first_downs_home',
 'third_downs_away',
 'third_downs_home',
 'fourth_downs_away',
 'fourth_downs_home',
 'passing_yards_away',
 'passing_yards_home',
 'rushing_yards_away',
 'rushing_yards_home',
 'total_yards_away',
 'total_yards_home',
 'comp_att_away',
 'comp_att_home',
 'sacks_away',
 'sacks_home',
 'rushing_attempts_away',
 'rushing_attempts_home',
 'fumbles_away',
 'fumbles_home',
 'int_away',
 'int_home',
 'turnovers_away',
 'turnovers_home',
 'penalties_away',
 'penalties_home',
 'redzone_away',
 'redzone_home',
 'drives_away',
 'drives_home',
 'def_st_td_away',
 'def_st_td_home',
 'possession_away',
 'possession_home',
 'score_away',
 'score_home',
 'Home_attempts_completed',
 'Home_attempts',
 'away_attempts_completed',
 'away_attempts',
 'YPPA_away',
 'YPPA_home',
 'Average_Yards_Per_Rush_Attempt_Home',
 'Average_Yards_Per_Rush_Attempt_Away',
 'Pts_Per_Drive_home',
 'Pts_Per_Drive_away',
 'Home_Result']

In [33]:
df = df.drop([
 'third_downs_away',
 'third_downs_home',
 'fourth_downs_away',
 'fourth_downs_home',
 'passing_yards_away',
 'passing_yards_home',
 'rushing_yards_away',
 'rushing_yards_home',
 'comp_att_away',
 'comp_att_home',
 'sacks_away',
 'sacks_home',
 'rushing_attempts_away',
 'rushing_attempts_home',
 'fumbles_away',
 'fumbles_home',
 'int_away',
 'int_home',
 'penalties_away',
 'penalties_home',
 'redzone_away',
 'redzone_home',
 'drives_away',
 'drives_home',
 'def_st_td_away',
 'def_st_td_home',
 'possession_away',
 'possession_home',
 'Home_attempts_completed',
 'Home_attempts',
 'away_attempts_completed',
 'away_attempts', axis = 1)

SyntaxError: invalid syntax (<ipython-input-33-db9ee70d603d>, line 33)

In [31]:
list(df.columns)

['first_downs_away',
 'first_downs_home',
 'total_yards_away',
 'total_yards_home',
 'turnovers_away',
 'turnovers_home',
 'score_away',
 'score_home',
 'YPPA_away',
 'YPPA_home',
 'Average_Yards_Per_Rush_Attempt_Home',
 'Average_Yards_Per_Rush_Attempt_Away',
 'Pts_Per_Drive_home',
 'Pts_Per_Drive_away',
 'Home_Result']